INSERT INTO `nombres_estados`(`id_estado`, `nombre_estado`) VALUES (1, 'Aguascalientes');
INSERT INTO `nombres_estados`(`id_estado`, `nombre_estado`) VALUES (2, 'Baja California');
INSERT INTO `nombres_estados`(`id_estado`, `nombre_estado`) VALUES (3, 'Baja California Sur');
INSERT INTO `nombres_estados`(`id_estado`, `nombre_estado`) VALUES (4, 'Campeche');
INSERT INTO `nombres_estados`(`id_estado`, `nombre_estado`) VALUES (5, 'Coahuila de Zaragoza');
INSERT INTO `nombres_estados`(`id_estado`, `nombre_estado`) VALUES (6, 'Colima');
INSERT INTO `nombres_estados`(`id_estado`, `nombre_estado`) VALUES (7, 'Chiapas');
INSERT INTO `nombres_estados`(`id_estado`, `nombre_estado`) VALUES (8, 'Chihuahua');
INSERT INTO `nombres_estados`(`id_estado`, `nombre_estado`) VALUES (9, 'Ciudad de México');
INSERT INTO `nombres_estados`(`id_estado`, `nombre_estado`) VALUES (10, 'Durango');
INSERT INTO `nombres_estados`(`id_estado`, `nombre_estado`) VALUES (11, 'Guanajuato');
INSERT INTO `nombres_estados`(`id_estado`, `nombre_estado`) VALUES (12, 'Guerrero');
INSERT INTO `nombres_estados`(`id_estado`, `nombre_estado`) VALUES (13, 'Hidalgo');
INSERT INTO `nombres_estados`(`id_estado`, `nombre_estado`) VALUES (14, 'Jalisco');
INSERT INTO `nombres_estados`(`id_estado`, `nombre_estado`) VALUES (15, 'México');
INSERT INTO `nombres_estados`(`id_estado`, `nombre_estado`) VALUES (16, 'Michoacán de Ocampo');
INSERT INTO `nombres_estados`(`id_estado`, `nombre_estado`) VALUES (17, 'Morelos');
INSERT INTO `nombres_estados`(`id_estado`, `nombre_estado`) VALUES (18, 'Nayarit');
INSERT INTO `nombres_estados`(`id_estado`, `nombre_estado`) VALUES (19, 'Nuevo León');
INSERT INTO `nombres_estados`(`id_estado`, `nombre_estado`) VALUES (20, 'Oaxaca');
INSERT INTO `nombres_estados`(`id_estado`, `nombre_estado`) VALUES (21, 'Puebla');
INSERT INTO `nombres_estados`(`id_estado`, `nombre_estado`) VALUES (22, 'Querétaro');
INSERT INTO `nombres_estados`(`id_estado`, `nombre_estado`) VALUES (23, 'Quintana Roo');
INSERT INTO `nombres_estados`(`id_estado`, `nombre_estado`) VALUES (24, 'San Luis Potosí');
INSERT INTO `nombres_estados`(`id_estado`, `nombre_estado`) VALUES (25, 'Sinaloa');
INSERT INTO `nombres_estados`(`id_estado`, `nombre_estado`) VALUES (26, 'Sonora');
INSERT INTO `nombres_estados`(`id_estado`, `nombre_estado`) VALUES (27, 'Tabasco');
INSERT INTO `nombres_estados`(`id_estado`, `nombre_estado`) VALUES (28, 'Tamaulipas');
INSERT INTO `nombres_estados`(`id_estado`, `nombre_estado`) VALUES (29, 'Tlaxcala');
INSERT INTO `nombres_estados`(`id_estado`, `nombre_estado`) VALUES (30, 'Veracruz de Ignacio de la Llave');
INSERT INTO `nombres_estados`(`id_estado`, `nombre_estado`) VALUES (31, 'Yucatán');
INSERT INTO `nombres_estados`(`id_estado`, `nombre_estado`) VALUES (32, 'Zacatecas');
